"""add content column to notion cache

Revision ID: fdd0621c3eb9
Revises: 877423bbd6f1
Create Date: 2025-09-20 18:21:32.465302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd0621c3eb9'
down_revision = '877423bbd6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_note_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notion_note_cache', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
